const navigationMenu = {
    nav: [{ title: "Home", path: '/' }, { title: "LG Data Fellowship", path: "/lgdatafellowship" }, { title: "Open Data Fellowship", path: "/womendatafellowship" }],
};

const aboutFellowship =
    '"Open Data Fellowship - Women Edition" is an initiative of Open Knowledge Nepal. The main motive behind the fellowship is to increase the number of women leaders in the field of open data in Nepal and use the existing expertise of different organizations to provide a good exposure to women and equip them with valuable work experience, confidence and skills that will help them to better understand the data ecosystem and potential opportunities. The fellowships offer the opportunity to connect with business groups, governments and individuals in the data community. \n' +
    "During the time of fellowship, the fellow will visit various host organizations for a half day in-house training which will be followed by the one-month placement in a respective organization. For the first edition, we will be selecting 10 women fellows. The application will be open until 10th March 2019, 12 PM NST.";

const aboutDataFellowship = {
    p1: `"Local Government (LG) Data Fellowship" is an initiative of Open Knowledge Nepal. The fellowship aims to assist municipal bodies in getting the data digitized and better used for decision-making. It offers the opportunity to work closely with various personnel in municipalities and other stakeholders. During the time of fellowship, the fellow will go through a series of training to sharpen their data skills and be placed at assigned municipalities to administer and operationalize Integrated Data Management System (IDMS). The application will be open until 15th October 2022, 12 PM NPT.`,
    p2: `Local Government Data Fellowship (LG Data Fellowship) is supported by the Data for Development Programme phase II, as part of the Integrated Data Management System for Local Government project. IDMS brings the data generated by the various departments and systems of the municipal office to the central hub. The fellowship will provide an opportunity for 3 individuals from project municipalities to gain experience in IDMS so that they can provide technical support to operationalize IDMS at the respective municipal offices. The fellowship program will run for 5 months.`,
    p3: `LG Data Fellows will bridge the technical gap and transfer skills of using IDMS to the municipalities. The fellows will also have an opportunity to network and participate in skill-enhancement events hosted by Open Knowledge Nepal and its partners. We encourage all interested and qualified candidates (especially youths, women, and members of an indigenous community) to apply for the fellowship.`
}
const whyShouldIJoin = [
    {
        title: "Understand data ecosystem",
        body:
            "Fellowship will provide you an opportunity to understand the data ecosystem and its various stakeholders.",
        icon: "icon-ecosystem",
    },
    {
        title: "Networking",
        body:
            "Fellowship will provide you an opportunity to broaden the horizon of your networking circle.\n",
        icon: "icon-Networking",
    },
    {
        title: "Enhance your confidence and skills",
        body:
            "Fellowship will provide you an opportunity to learn, enhance new skills and boost your confidence level through weekly group mentoring and in-house training.",
        icon: "icon-achievement",
    },
    {
        title: "Gain valuable work experience",
        body:
            "During the time of fellowship, you will get an opportunity to work hand to hand with different leading organizations of their respective field.  This one month of valuable work experience will surely help in your career ahead.",
        icon: "icon-experience",
    },
    {
        title: "Grab potential opportunities",
        body:
            "Explore the various potential opportunities in the field of data with the help of mentors. Grab it for the betterment of your career.",
        icon: "icon-opportunities",
    },
    {
        title: "Be the role model",
        body:
            "Be the inspirational role model by being a Open Data Women Fellow of first batch. Also set an example for the next batch.",
        icon: "icon-role-model",
    },
];

const FAQ = [
    {
        title: " Who can apply to become a fellow?",
        body:
            "Any woman who is a current resident of Nepal are eligible to apply. But we encourage final year students who are currently pursuing their bachelor’s degree.",
    },
    {
        title: "How can I apply?",
        body:
            "Complete the online application, selected fellow will be informed by 20th March 2019.",
    },
    {
        title: "How many fellows will be recruited this year?",
        body: "We will be recruiting only 10 fellows for the first batch.",
    },
    {
        title: "How much time are the fellows expected to dedicate?",
        body:
            "Fellows are expected to dedicate one and half months. One month for working in a respective organization  and a half month for training, meetup and various get-together events.",
    },
    {
        title: "How is the training programme structured?",
        body:
            "Half day in-house training at the host organization and one month project based placement. The fellows will be provided with some stipend to cover travel and lunch.",
    },
    {
        title: "What kind of activities will the fellows carry out?",
        body:
            "Fellows will go through a series of training and workshops to sharpen their data and communication skills before the placement. At host organization, they can work on various kinds of projects like: opening up datasets, case studies, research, data-driven blog posts, developing open source software libraries etc. But we encourage to work on projects that can match with the respective organization’s objectives.",
    },
];

const hostLogos = [
    {
        url: "/hosts/accountabilitylab.png",
        name: "Accountailtiy Lab",
        order: 1,
    },
    {
        url: "/hosts/bikashudahyami.png",
        name: "BikashUdayami",
        order: 1,
    },
    {
        url: "/hosts/cleanupNepal.png",
        name: "Cleanup Nepal",
        order: 1,
    },
    {
        url: "/hosts/F4DM.png",
        name: "",
        order: 1,
    },
    {
        url: "/hosts/freedomForum.png",
        name: "Freedom Forum",
        order: 1,
    },
    {
        url: "/hosts/KLL.png",
        name: "Kathmandu living Labs",
        order: 1,
    },
    {
        url: "/hosts/pathway.png",
        name: "Pathway Technologies",
        order: 1,
    },
    {
        url: "/hosts/younginnovation.png",
        name: "Young Innovation",
        order: 1,
    },
    {
        url: "/hosts/yuwa.png",
        name: "Yuwa",
        order: 1,
    },
];

const footerLink = [
    {
        title: "About Us",
        url: "http://oknp.org/",
        icon: "icon-about-us",
    },
    {
        title: "Email Us",
        url: "info@oknp.org",
        icon: "icon-email",
    },
    {
        title: "Twitter",
        url: "https://twitter.com/okfn_np",
        icon: "icon-twitter",
    },
    {
        title: "Facebook",
        url: "https://www.facebook.com/okfnepal/",
        icon: "icon-twitter",
    },
];

const applicationSummary = {
    title:
        "Application must be completed online and consists of the following components:",
    items: [
        { title: "Personal information", summary: "Include and share personal information", imageUrl: "/information/information.png" },
        { title: "Motivation Section", summary: "Share what motivates you to apply", imageUrl: "/information/goals.png" },
        { title: "CV/Resume", summary: "in pdf CV no longer than 2 pages", imageUrl: "/information/cv.png" },
    ],
};

const selectionCriteria = {
    title: "Fellow must:",
    items: [
        {
            item:
                "Be local from the project municipalities or willing to relocate.",
        },
        {
            item:
                "Be 30 years old or younger by the time of applying.",
        },
        {
            item:
                "Have a bachelor's or diploma degree IT related courses - Engineering, BSc CSIT, BCA, BIM, etc.",
        },
        {
            item:
                "Have knowledge of or interest in data sciences, open technology, and open data.",
        },
        {
            item:
                "Be curious to work with the municipality and IT officers.",
        },
        {
            item:
                "Have strong knowledge and interest in learning data-related technologies.",
        },
        {
            item:
                "Have good communication skills in Nepali and English.",
        },
        { item: "Be a team player and have collaborative skills." },
    ],
};

const keyResponsibilities = {
    title: "Fellows will be responsible for:",
    items: [
        {
            item:
                "Working closely with the municipal personnel to clean, standardize and integrate datasets into IDMS.",
        },
        {
            item:
                "Collaborating with the IT officer and municipal data focal personnel.",
        },
        {
            item:
                "Supporting assigned municipality to administer and operationalize IDMS.",
        },
        {
            item:
                "Reporting and documenting the progress, challenges, and learning",
        },
    ],
};

const benifits = {
    title: "Fellowship Benefits",
    items: [
        {
            title: "Upskilling",
            body:
                "Training on data pipeline and various other data management aspects.",
            imageUrl: "/information/training.png",
            summary: "Enhance your data skill via training and workshop",
        },
        {
            title: "Earning",
            body: "Monthly stipend of NRP 30,000 per month.",
            imageUrl: "/information/money.png",
            summary: "Monthly stipend for period of fellowship",
        },
        {
            title: "Networking",
            body:
                "Training on data pipeline and various other data management aspects.",
            imageUrl: "/information/networking.png",
            summary: "Opportunity to work closely with government officials",
        },
        {
            title: "Mentoring",
            body:
                "Resolute mentoring from OKN team members.",
            imageUrl: "/information/team.png",
            summary: "Receive resolute mentoring from OKN team members",
        },
        {
            title: "Certificate",
            body: "Graduation certificate of the fellowship.",
            imageUrl: "/information/certification.png",
            summary: "Grab the graduation certificate of the fellowship",
        },
        {
            title: "Placement",
            body: "Get the opportunity of potential job placement.",
            imageUrl: "/information/interview.png",
            summary: "Get the opportunity of potential job placement",

        },
    ],
};

const projectMunicipality = [
    {
        Province: "Madhesh Province",
        District: "Parsa",
        LocalGovernment: "Birgunj Metropolitan City",
    },
    {
        Province: "Lumbini Province",
        District: "Dang",
        LocalGovernment: "Tulsipur Sub-Metropolitan City",
    },
    {
        Province: "Karnali Province",
        District: "Surkhet",
        LocalGovernment: "Lekbesi Municipality",
    },
];

const timelineData = [
    {
        text: 'Application Opens',
        date: 'September 25, 2022',
        category: {
            tag: 'opening',
            color: '#018f69'
        },
        // link: {
        //     url:
        //         'https://medium.com/@popflorin1705/javascript-coding-challenge-1-6d9c712963d2',
        //     text: 'Read more'
        // }
    },
    {
        text: 'Application Deadline',
        date: 'October 15, 2022',
        category: {
            tag: 'deadline',
            color: '#E17B77'
        },
    },
    {
        text: 'Selected Fellows Announcement',
        date: 'October 20, 2022 ',
        category: {
            tag: 'result',
            color: '#1B3E76'
        },
    },
]

const heroContent = {
    description: "The LG Data fellowship aims to assist municipal bodies in getting the data digitized and better used for decision-making. It offers the opportunity to work closely with various personnel in municipalities and other stakeholders. During the fellowship, the fellow will go through a series of training to sharpen their data skills and be placed at assigned municipalities to administer and operationalize Integrated Data Management System (IDMS). The application will be open until 15th October 2022, 12 PM NPT."
}

export {
    navigationMenu,
    whyShouldIJoin,
    aboutFellowship,
    FAQ,
    hostLogos,
    footerLink,
    applicationSummary,
    projectMunicipality,
    selectionCriteria,
    keyResponsibilities,
    benifits,
    aboutDataFellowship,
    timelineData,
    heroContent
};
